modLoader="javafml"
loaderVersion="[46,)"
license="MIT"
issueTrackerURL="https://github.com/Viola-Siemens/EveryXHerbs/issues"

[[mods]]
modId="everyxherbs"
version="${file.jarVersion}"
displayName="EveryXHerbs"
logoFile="logo.png"
credits="Liu Dongyu"
authors="Hexagram"
description='''

'''

[[dependencies.everyxherbs]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.everyxherbs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
